import type { AgentModelRef, AssetCanvasTextGenerationResponse, ToolJob } from "../shared/contracts.js";
import type { CanvasDocumentDetail, CanvasDocumentGenerationRequest, CanvasDocumentGenerationResponse } from "../shared/canvas-document.js";
import type { CanvasBoardDetail, CanvasWorkspaceDetail, CanvasWorkspaceIndex } from "../shared/canvas-workspace.js";
import { request } from "./api.js";

const base = (projectId: string) => `/projects/${encodeURIComponent(projectId)}/canvas`;
const query = (documentId?: string) => documentId ? `?documentId=${encodeURIComponent(documentId)}` : "";
export const getCanvasWorkspace = (id: string): Promise<CanvasWorkspaceDetail> => request(`${base(id)}/workspace`);
export const exportCanvasAsset = (id: string, assetId: string): Promise<{ assetId: string }> => request(`${base(id)}/assets/${encodeURIComponent(assetId)}/library`, { method: "POST" });
export const setMainCanvasDocument = (id: string, documentId: string): Promise<void> => request(`${base(id)}/main-document`, { method: "PUT", body: JSON.stringify({ documentId }) });
export const getCanvasBoard = (id: string, boardId: string): Promise<CanvasBoardDetail> => request(`${base(id)}/boards/${encodeURIComponent(boardId)}`);
export const saveCanvasBoard = (id: string, detail: CanvasBoardDetail): Promise<CanvasBoardDetail> => request(`${base(id)}/boards/${encodeURIComponent(detail.board.id)}`, { method: "PUT", body: JSON.stringify(detail) });
export const createCanvasBoard = (id: string, name: string): Promise<CanvasWorkspaceIndex> => request(`${base(id)}/boards`, { method: "POST", body: JSON.stringify({ name }) });
export const changeCanvasBoard = (id: string, boardId: string, patch: { name?: string; direction?: number }): Promise<CanvasWorkspaceIndex> => request(`${base(id)}/boards/${encodeURIComponent(boardId)}`, { method: "PATCH", body: JSON.stringify(patch) });
export const deleteCanvasBoard = (id: string, boardId: string): Promise<CanvasWorkspaceIndex> => request(`${base(id)}/boards/${encodeURIComponent(boardId)}`, { method: "DELETE" });
export const createCanvasDocument = (id: string, title: string): Promise<CanvasDocumentDetail> => request(`${base(id)}/documents`, { method: "POST", body: JSON.stringify({ title }) });
export const getCanvasDocument = (id: string, documentId?: string): Promise<CanvasDocumentDetail | null> => request(`${base(id)}${query(documentId)}`);
export const saveCanvasDocument = (id: string, detail: CanvasDocumentDetail, documentId?: string): Promise<CanvasDocumentDetail> => request(`${base(id)}${query(documentId)}`, { method: "PUT", body: JSON.stringify(detail) });
export const insertCanvasImage = (id: string, documentId: string, assetId: string): Promise<CanvasDocumentDetail> => request(`${base(id)}/documents/${encodeURIComponent(documentId)}/images`, { method: "POST", body: JSON.stringify({ assetId }) });
export const listCanvasJobs = (id: string): Promise<ToolJob[]> => request(`${base(id)}/jobs`);
export const generateCanvasMedia = (id: string, boardId: string, nodeId: string): Promise<ToolJob> => request(`${base(id)}/boards/${encodeURIComponent(boardId)}/nodes/${encodeURIComponent(nodeId)}/generate`, { method: "POST" });
export const cancelCanvasJob = (id: string, jobId: string): Promise<ToolJob> => request(`${base(id)}/jobs/${encodeURIComponent(jobId)}/cancel`, { method: "POST" });
export const generateCanvasText = (id: string, instruction: string, model: AgentModelRef): Promise<AssetCanvasTextGenerationResponse> => request(`${base(id)}/text/generate`, { method: "POST", body: JSON.stringify({ instruction, model }) });
export const generateCanvasDocument = (id: string, documentId: string, input: CanvasDocumentGenerationRequest): Promise<CanvasDocumentGenerationResponse> => request(`${base(id)}/documents/${encodeURIComponent(documentId)}/generate`, { method: "POST", body: JSON.stringify(input) });
