import {
  AddFolderIcon,
  AddIcon,
  AltArrowDownIcon,
  AltArrowLeftIcon,
  AltArrowRightIcon,
  ArrowToDownRightIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  BoxIcon,
  BoxMinimalisticIcon,
  BranchingPathsDownIcon,
  ClapperboardIcon,
  CloseCircleIcon,
  CloseIcon,
  Code2Icon,
  CodeFileIcon,
  CopyIcon,
  CursorIcon,
  DownloadIcon,
  DownloadMinimalisticIcon,
  FileTextIcon,
  FlagIcon,
  FolderIcon,
  FolderOpenIcon,
  GamepadIcon,
  GlobalIcon,
  GalleryIcon,
  HistoryIcon,
  HomeIcon,
  LayersIcon,
  LightbulbIcon,
  MagicWandIcon,
  MagnifierIcon,
  MaximizeIcon,
  MenuDotsIcon,
  MinusIcon,
  MonitorIcon,
  MoveToFolderIcon,
  MusicNoteIcon,
  PenIcon,
  PenNewSquareIcon,
  PlayIcon,
  PlugCircleIcon,
  ProgrammingIcon,
  RefreshIcon,
  RestartIcon,
  SettingsIcon,
  ShareIcon,
  SidebarMinimalisticIcon,
  SidebarIcon,
  SliderHorizontalIcon,
  SmartphoneIcon,
  SortVerticalIcon,
  SquareArrowRightUpIcon,
  StarsIcon,
  StopCircleIcon,
  TabletIcon,
  TrashBinTrashIcon,
  UploadIcon,
  UserRoundedIcon,
  VideoFrameIcon,
  VideocameraIcon,
  WiFiIcon,
  WiFiOffIcon,
} from "@solar-icons/react/linear";
import type { Icon as SolarIcon, IconProps } from "@solar-icons/react/lib/types";
import { createElement, forwardRef } from "react";

export type IconComponent = SolarIcon;

export const Check = forwardRef<SVGSVGElement, IconProps>(function Check({ size = 24, ...props }, ref) {
  return createElement("svg", { ref, width: size, height: size, viewBox: "0 0 24 24", fill: "none", ...props }, createElement("path", { d: "M5 12.5L9.2 16.5L19 7", stroke: "currentColor", strokeWidth: "1.5", strokeLinecap: "round", strokeLinejoin: "round" }));
});

export const Circle = forwardRef<SVGSVGElement, IconProps>(function Circle({ size = 24, ...props }, ref) {
  return createElement("svg", { ref, width: size, height: size, viewBox: "0 0 24 24", fill: "none", ...props }, createElement("circle", { cx: "12", cy: "12", r: "9", stroke: "currentColor", strokeWidth: "1.5" }));
});

export const CircleDot = forwardRef<SVGSVGElement, IconProps>(function CircleDot({ size = 24, ...props }, ref) {
  return createElement("svg", { ref, width: size, height: size, viewBox: "0 0 24 24", fill: "none", ...props }, createElement("circle", { cx: "12", cy: "12", r: "9", stroke: "currentColor", strokeWidth: "1.5" }), createElement("circle", { cx: "12", cy: "12", r: "3", fill: "currentColor" }));
});

export const Square = forwardRef<SVGSVGElement, IconProps>(function Square({ size = 24, ...props }, ref) {
  return createElement("svg", { ref, width: size, height: size, viewBox: "0 0 24 24", ...props }, createElement("rect", { x: "7", y: "7", width: "10", height: "10", rx: "1", fill: "currentColor" }));
});

export const Hand = forwardRef<SVGSVGElement, IconProps>(function Hand({ size = 24, ...props }, ref) {
  return createElement("svg", { ref, width: size, height: size, viewBox: "0 0 24 24", fill: "none", ...props }, createElement("path", { d: "M18 11V7.5a1.5 1.5 0 0 0-3 0V10m0-2.5V6a1.5 1.5 0 0 0-3 0v4m0-3V5.5a1.5 1.5 0 0 0-3 0V11m0-3.5a1.5 1.5 0 0 0-3 0V13l-1.2-1.2a1.7 1.7 0 0 0-2.4 2.4l4 4A6 6 0 0 0 10.6 20H13a5 5 0 0 0 5-5v-4Z", stroke: "currentColor", strokeWidth: "1.5", strokeLinecap: "round", strokeLinejoin: "round" }));
});

export {
  AddFolderIcon as FolderPlus,
  AddIcon as Plus,
  AltArrowDownIcon as ChevronDown,
  AltArrowLeftIcon as ChevronLeft,
  AltArrowRightIcon as ChevronRight,
  DownloadMinimalisticIcon as ArrowDownToLine,
  SortVerticalIcon as ArrowDownUp,
  ArrowToDownRightIcon as CornerDownRight,
  ArrowLeftIcon as ArrowLeft,
  ArrowRightIcon as ArrowRight,
  SquareArrowRightUpIcon as ExternalLink,
  ArrowUpIcon as ArrowUp,
  BoxIcon as Box,
  BoxMinimalisticIcon as Package,
  BranchingPathsDownIcon as GitBranch,
  PenNewSquareIcon as MessageSquarePlus,
  ClapperboardIcon as Clapperboard,
  CloseCircleIcon as CircleX,
  CloseIcon as X,
  Code2Icon as Code2,
  CodeFileIcon as FileCode2,
  CopyIcon as Copy,
  CursorIcon as MousePointer2,
  DownloadIcon as Download,
  FileTextIcon as FileText,
  FlagIcon as Flag,
  FolderIcon as Folder,
  FolderOpenIcon as FolderOpen,
  GamepadIcon as Gamepad2,
  GlobalIcon as Globe2,
  GalleryIcon as Image,
  VideoFrameIcon as Film,
  HistoryIcon as History,
  HomeIcon as House,
  LayersIcon as Layers3,
  LightbulbIcon as Lightbulb,
  MaximizeIcon as Maximize,
  MenuDotsIcon as MoreHorizontal,
  MinusIcon as Minus,
  MonitorIcon as Monitor,
  MoveToFolderIcon as FolderInput,
  MusicNoteIcon as Music2,
  PenIcon as Pencil,
  PenNewSquareIcon as FilePenLine,
  PlayIcon as Play,
  PlugCircleIcon as Plug,
  RefreshIcon as LoaderCircle,
  RefreshIcon as RefreshCw,
  RestartIcon as RotateCcw,
  MagnifierIcon as Search,
  ShareIcon as Share2,
  SidebarMinimalisticIcon as PanelLeftClose,
  SidebarIcon as PanelLeftOpen,
  SliderHorizontalIcon as SlidersHorizontal,
  SmartphoneIcon as Smartphone,
  StarsIcon as Sparkles,
  StopCircleIcon as CircleStop,
  TabletIcon as Tablet,
  ProgrammingIcon as Terminal,
  TrashBinTrashIcon as Trash2,
  UploadIcon as Upload,
  UserRoundedIcon as UserRound,
  VideocameraIcon as Video,
  MagicWandIcon as WandSparkles,
  WiFiIcon as Wifi,
  WiFiOffIcon as WifiOff,
  SettingsIcon as Wrench,
};
